version: "3.7"
networks:
  gateway:

services:
  # ubuntu20:
  #   image: ubuntu:20.10
  #   container_name: ubuntu20
  #   restart: always
  #   tty: true
  #   volumes:
  #     - /Users/darren/go:/go
  #     - /Users/darren/go:/src
  #     - /Users/darren/Downloads:/var/Downloads
  #   networks:
  #     - gateway
  #   ports:
  #     - 9988:9988
 ########################  mysql5.6  ########################
  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./:/configs
      - ./mysqlconf:/etc/mysql/conf.d
      - ./mysqldata:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf
    restart: 'always'
    command: [
      '--character-set-server=utf8',
    ]
    networks:
      - gateway
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "--protocol=tcp"]
      timeout: 20s
      interval: 1s
      retries: 20